# Generated by Django 4.0.1 on 2022-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='cut_url',
            field=models.CharField(max_length=20, verbose_name='сокращеный урл'),
        ),
        migrations.AlterField(
            model_name='url',
            name='origin_url',
            field=models.URLField(unique=True, verbose_name='оригинальй урл'),
        ),
    ]
