# Generated by Django 4.0.1 on 2022-01-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_url_cut_url_alter_url_origin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='price',
            field=models.IntegerField(default=65),
        ),
    ]
